services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    volumes:
      - backend-data:/app/data
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite:///app/data/database.db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
    driver: local