services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/albertpardo/ft_transcendence.git
    branch: main
    rootDir: frontend
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    ports: 
      - 3000

  - type: web
    name: api-gateway
    env: docker
    repo: https://github.com/albertpardo/ft_transcendence.git
    branch: main
    rootDir: backend/api-gateway
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/api-gateway/**
    nvVars:
      - key: JWT_SECRET
        value: ""
      - key: API_BASE_URL
        value: ""
    healthCheckPath: /health
    ports:
      - 8443

  - type: web
    name: user_management
    env: docker
    repo: https://github.com/albertpardo/ft_transcendence.git
    branch: main
    rootDir: backend/microservices/user_management
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/microservices/user_management/**
    envVars:
      - key: PORT
        value: "9001"
    healthCheckPath: /health
    ports:
      - 9001
